### ISSUE TITLE
Remove for loop from job script

### ISSUE THREAD

**Issue by njhunsak** [danielasay/psych516#1]
Remove this for loop:

https://github.com/danielasay/psych516/blob/01626b735a8da31ec601d7130b77519b5eb52135/T1_preprocessing_job_script.sh#L15

Your subject ID comes from the "command line variable" set when you submit your batch script. Instead of using ${i}, you need to use ${1}:

https://github.com/danielasay/psych516/blob/01626b735a8da31ec601d7130b77519b5eb52135/T1_preprocessing_job_script.sh#L28

Remove the end of your for loop:

https://github.com/danielasay/psych516/blob/01626b735a8da31ec601d7130b77519b5eb52135/T1_preprocessing_job_script.sh#L59

You also don't need multiple change directories.

**Comment by njhunsak** [comment]
Here's some more information about command line arguments. Command line arguments are commonly used when you want to pass a variable from one script to another. In our case, command line arguments are used to pass a variable from the 'batch' script to a 'job' script. 

If you run the command:

```
sbatch job.sh $SUBJID
```

Command line variables are set automatically by the system:

* $0 is the name of the bash script you are running (i.e., script.sh)
* $1 - $9 are the first 9 arguments to the bash script (i.e., $SUBJID)

```
sbatch job.sh $SUBJID $SES
```

If you had to include session information according to BIDs format:

* $0 is the name of the bash script you are running (i.e., script.sh)
* $1 is the first argument to the bash script (i.e., $SUBJID)
* $2 is the second argument to the bash script (i.e., $SES)

The variables $1 and $2 then can be used within the job.sh file.

**Comment by njhunsak** [comment]
These lines of code are not needed in your script:

https://github.com/danielasay/psych516/blob/7f25b62ae0ff4828b8e485886ffbe778212b1e1e/T1_preprocessing_job_script.sh#L25

https://github.com/danielasay/psych516/blob/7f25b62ae0ff4828b8e485886ffbe778212b1e1e/T1_preprocessing_job_script.sh#L37

https://github.com/danielasay/psych516/blob/7f25b62ae0ff4828b8e485886ffbe778212b1e1e/T1_preprocessing_job_script.sh#L48

Also, where have you set your FreeSurfer environmental variable? There should be some information around line 9 that contains the FreeSurfer environmental variables or `freesurfer` alias.

**Comment by njhunsak** [comment]
You also need to remove `done` since there's no for loop in your job script.

https://github.com/danielasay/psych516/blob/7f25b62ae0ff4828b8e485886ffbe778212b1e1e/T1_preprocessing_job_script.sh#L56

**Comment by danielasay** [comment]
Thanks for the help. I went ahead and updated my scripts on Github. Let me
know if there is anything else I can fix.

Best,

Daniel

**Comment by njhunsak** [comment]
Your old code had the correct time limit.  You'll get in trouble with the supercomputer managers if you ask for too many resources:

https://github.com/danielasay/psych516/blob/ba0795ecfe2bbcee816a263ac12b6a22af602c8a/T1_preprocessing_job_script.sh#L3

**Comment by danielasay** [comment]
Whoops! I got this job mixed up with the recon_all job. This baby's sleep
schedule has definitely messed with my cognition haha.

Thanks,

Daniel
