### ISSUE TITLE
freesurfer recon-all

### ISSUE THREAD

**Issue by njhunsak** [danielasay/psych516#3]
All your code looks good. However, there are a still a few issues with Week 4's assignment:

1. I have serious concerns about how you are organizing your data.

https://github.com/danielasay/psych516/blob/33278b5af976c4b0c6585425b24b5746a3e724ce/recon_all_bigvent_job_script.sh#L14

Your derivative directory should look something like this:

```
./deriv
├── freesurfer_subjects
│   ├── sub-FREAD001
│   ├── sub-FREAD002
│   ├── sub-FREAD003
│   ├── sub-FREAD004
│   ├── sub-FREAD005
│   ├── sub-FREAD006
│   ├── sub-FREAD007
│   ├── sub-FREAD008
│   ├── sub-FREAD009
│   ├── sub-FREAD010
│   ├── sub-FREHC001
│   ├── sub-FREHC002
│   ├── sub-FREHC003
│   ├── sub-FREHC004
│   ├── sub-FREHC005
│   ├── sub-FREHC006
│   ├── sub-FREHC007
│   ├── sub-FREHC008
│   ├── sub-FREHC009
│   ├── sub-FREHC010
│   ├── sub-FREHC011
│   ├── sub-FREHC012
│   ├── sub-FREHC013
│   ├── sub-FREHC014
│   ├── sub-FREHC015
│   ├── sub-FREHC016
│   ├── subjects.txt
│   └── tablefiles
├── freesurfer_subjects_bigventricles
│   ├── sub-FREAD001
│   ├── sub-FREAD002
│   ├── sub-FREAD003
│   ├── sub-FREAD004
│   ├── sub-FREAD005
│   ├── sub-FREAD006
│   ├── sub-FREAD007
│   ├── sub-FREAD008
│   ├── sub-FREAD009
│   ├── sub-FREAD010
│   ├── sub-FREHC001
│   ├── sub-FREHC002
│   ├── sub-FREHC003
│   ├── sub-FREHC004
│   ├── sub-FREHC005
│   ├── sub-FREHC006
│   ├── sub-FREHC007
│   ├── sub-FREHC008
│   ├── sub-FREHC009
│   ├── sub-FREHC010
│   ├── sub-FREHC011
│   ├── sub-FREHC012
│   ├── sub-FREHC013
│   ├── sub-FREHC014
│   ├── sub-FREHC015
│   ├── sub-FREHC016
│   ├── subjects.txt
│   └── tablefiles
└── pT1
    ├── sub-FREAD001
    ├── sub-FREAD002
    ├── sub-FREAD003
    ├── sub-FREAD004
    ├── sub-FREAD005
    ├── sub-FREAD006
    ├── sub-FREAD007
    ├── sub-FREAD008
    ├── sub-FREAD009
    ├── sub-FREAD010
    ├── sub-FREHC001
    ├── sub-FREHC002
    ├── sub-FREHC003
    ├── sub-FREHC004
    ├── sub-FREHC005
    ├── sub-FREHC006
    ├── sub-FREHC007
    ├── sub-FREHC008
    ├── sub-FREHC009
    ├── sub-FREHC010
    ├── sub-FREHC011
    ├── sub-FREHC012
    ├── sub-FREHC013
    ├── sub-FREHC014
    ├── sub-FREHC015
    └── sub-FREHC016
```

2. I'm not sure what image I should be looking at for the assignment. Please better organize your Github posts. Downloading your repository locally and using Github Desktop will greatly help.

https://github.com/danielasay/psych516/blob/master/sub-FREAD002_T1.png
https://github.com/danielasay/psych516/blob/master/sub-FREAD002_bigvent.png
https://github.com/danielasay/psych516/blob/master/sub-FREAD002_reg_vent.png
https://github.com/danielasay/psych516/blob/master/sub-FREHC007.png

https://desktop.github.com

**Comment by danielasay** [comment]
I re-downloaded the raw data and I'm pushing it through the pipeline again
with some different formatting so that the data is organized better. I
chose to push it through the pipeline again because I somehow ended up with
some missing data for a couple of participants, so I figured I'd kill two
birds with one stone.

I created a branch on my github called "recon all assignment" where all of
the scripts, tables, and screenshots for this assignment are. I also
re-uploaded the images requested for the assignment.

I hope this covers everything. Please let me know if there are any
additional issues that I should address.

Thank you!

Daniel

**Comment by danielasay** [comment]
I uploaded the revised scripts I used to push the data through the
processing pipeline to Github. The organization is much clear now. I think
I have everything updated for this assignment. Please let me know if
there's anything else I need to do.

Thanks!

Daniel

**Comment by njhunsak** [comment]
Everything looks great for this assignment.
